--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["UIBlox-8b8d973a-75e6a511"]["UIBlox"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package